# Introduction to Numerical Methods in Macroeconomics and Python

**Table of Contents:**

- [Numerical Methods: what are they and why do we need them](#Numerical-Methods:-what-are-they-and-why-do-we-need-them)
    - [Perturbation methods](#Perturbation-methods)
    - [Projection methods](#Projection-methods)
- [Python](#Python)
    - [Introduction](#Introduction)
    - [The need for modules](#The-need-for-modules)
    - [Numpy](#Numpy)
    - [Scipy](#Scipy)
    - [Matplotlib](#Matplotlib)

## Numerical Methods: what are they and why do we need them

In Macroeconomics we are often asked to solve for the equilibrium of a model.
A model consists of a system of (often nonlinear) equations in some unknowns.
Because of nonlinearities, it is often difficult or impossible to obtain closed-form solutions.
We do not want to keep talking about models we can solve analytically, because that would be quite a restricted set of models.
Therefore, we need numerical methods to explore the solutions to complicated models.

These TA sessions focus on exploring some popular numerical methods that are useful in Macroeconomics.
We will focus on discrete-time models, as these present non-trivial challenges relative to models in continuous-time.

Broadly speaking, we can categorize solutions methods in two families:

- perturbation methods; and
- projection methods.

### Perturbation methods

For nonlinear models that feature smooth functions, we can get fast and efficient solutions by approximating the system of equations around some specific point.
We can write any rational-expectations model in the following way:
$$
f \left( X_{t-1}, X_{t}, X_{t+1} \right) = 0,
$$
where I assumed that the model is deterministic.
Stochastic models with rational expectations are similarly written (notably with an expectation operator), and are similarly treated.
The solution to such a system of equations (assuming it exists and it is unique) is written as
$$
X_{t+1} = g \left( X_{t}, X_{t-1} \right),
$$
where $g(\cdot)$ is a set of policy functions.

What we can do with such a system is to take a Taylor expansion of $f(\cdot)$ around a point.
It is common to consider the first-order approximation (denote it with $\hat{f}$) around the deterministic steady state of the model.
Instead of solving $f=0$, we can solve $\hat{f}=0$.
As this new system is linear, we know we can easily solve it: the solution will be a linear policy function $\hat{g}$ that will hold only in an arbitrary (small) neighborhood of the steady state.

For example, we know how to analytically solve the textbook version of the RBC model with full capital depreciation (i.e., $\delta=1$).
If $\delta \neq 1$, then we need to use numerical methods.

In this course, we will not deal with perturbation methods.
We will go hands-on with them in the next Macro course.

If we introduce discontinuities or non-differentiable equations in the model (e.g., borrowing constraints or discrete control variables), we cannot reliably take the Taylor expansion of a model.
This justifies the interest in projection methods to solve models.

### Projection methods

Projection methods try to force their way through a solution, mostly through a trial-and-error procedure.
The intuition is very similar to the [Newton algorithm](https://en.wikipedia.org/wiki/Newton%27s_method) to find roots of a function: you start with a proposal for the solution and you check if it works.
If it does not, then you use some (educated) criterion to create a new proposal.
You repeat the procedure until you arrive to the solution.

The difficulty in the case of Macroeconomics is that the proposals we are dealing with are not points in a space of scalars, but are points in a space of functions.
This might not be clear at first, as we are going to work with numerical representations of functions.

The clearest application of the projection method is probably the Aiyagari (1994) model.
In such model, we should find a capital-remuneration rate $r_t$ such that all markets (goods, labor, capital) are in equilibrium.
We will see the details in a dedicated TA session, but here is the gist of it.
We enter the $n$-th iteration with a proposal $r_{t}^{(n)}$.
We check if it clears the capital market: 
- if it does not because there is excess demand, we know we should have $r_{t}^{(n+1)} > r_{t}^{(n)}$.
- if it does not because there is excess supply, we know we should have $r_{t}^{(n+1)} < r_{t}^{(n)}$.

A common critique to projection methods is the following: it is often the case that we cannot verify the solution we reach is unique (e.g., sunspots).
So it might happen that you have models where the procedure never converges anywhere, or where the procedure converges to "weird" solutions.
A way to deal with this is to carry out extensive (and sometimes painful) sensitivity analysis.

### Notable, classical examples

- The deterministic Neoclassical Growth Model
- The stochastic Neoclassical Growth Model
- [Huggett (1993)](https://doi.org/10.1016/0165-1889(93)90024-M)
- [Aiyagari (1994)](https://doi.org/10.2307/2118417)
- [Krussell and Smith (1998)](https://doi.org/10.1086/250034)
- [Reiter (2009)](https://doi.org/10.1016/j.jedc.2008.08.010)

## Python

### Introduction

Python is a programming language.
It is not a mathematics-oriented language in and of itself.
It is a general-purpose language, meaning we can do pretty much what we want with it.
Here is a list of what humanity did with Python:

- Dropbox (Source: [Dropbox Blog](https://blogs.dropbox.com/tech/2018/09/how-we-rolled-out-one-of-the-largest-python-3-migrations-ever/))
- Image editing ([The GNU Image Manipulation Program](https://www.gimp.org/))
- Vector graphics ([Inkscape](https://inkscape.org/))
- 3D modeling ([Blender](https://www.blender.org/))
- Desktop publishing ([Scribus](https://www.scribus.net/))
- Web pages ([Reddit](https://www.reddit.com/), Source: [Reddit Blog](https://redditblog.com/2005/12/05/on-lisp/))

We could spend ages trying to understand all the details on how Python works, and it is very easy for me to get lost in technical explanations.
Instead, let's have a look at the very simple things Python allows us to do.

In [2]:
2 + 1 - 7

-4

In [3]:
3 * 2 / 4

1.5

In [4]:
print('Hello world!')

Hello world!


In [5]:
print("'This' is a string")

'This' is a string


In [6]:
print('The Answer to the Ultimate Question of Life, The Universe, and Everything is 6 * 9 = 42 (although 6 * 9 = {})'.format(6*9))

The Answer to the Ultimate Question of Life, The Universe, and Everything is 6 * 9 = 42 (although 6 * 9 = 54)


In [7]:
print('This ---> {}\nis a list'.format(['a', 'b', 'c']))

This ---> ['a', 'b', 'c']
is a list


In [10]:
print('This ---> {}\nis a tuple'.format(('a', 'b', 'c')))

This ---> ('a', 'b', 'c')
is a tuple


In [12]:
print('This ---> {}\nis a dictionary'.format({'a': 1, 'b': 2, 'c': 3}))

This ---> {'a': 1, 'b': 2, 'c': 3}
is a dictionary


### The need for modules

Modules are sets of functions and classes that are oriented towards a given goal.
Say you have a bunch of functions that altogether serve one purpose (e.g., connect to a website and download stuff acccording to some criteria).
Then your bunch may be collected into a module.
Packages are sets of modules.

Here are some packages we, as economists, will encounter most often:

- `numpy` (N-dimensional arrays)
- `scipy` (mathematics and statistics)
- `pandas` (dataframes, as in R or Stata)
- `matplotlib` (2D plotting)
- `beautifulsoup4` (HTML web scraping)
- `selenium` (Chrome-driven web scraping)
- `bokeh` (interactive data visualization)

How you install these packages in your computer depends on your Operating System.
If you have a Windows or macOS machine, then you are most likely using the Anaconda distribution, which bundles most packages and hence they should already be on your computer.
If you use a Debian-based Linux distribution, you may want to check out your package manager for these modules.

If your package distribution (e.g., Anaconda, APT) does not give you access to a given module, you can use `pip`, which is Python's integrated package manager.

#### How do we use modules/packages?

At the very beginning of your `.py` file, you should include `import` statements.
These statements instruct the Python interpreter to use definitions that are found in those packages.
Note that you can also use shorthands for accessing functions inside modules.

In what follows, we see some notable packages and some of their functions.
The point here is not to teach everything you need about all the packages.
This is just to show minimal working examples, so to get familiar with syntax and some basic functions.

### NumPy

Python does not know what a vector or a matrix are.
The goal of NumPy is to add support for multi-dimensional arrays, together with basic mathematical functions.
In other words, NumPy brings basic Matlab-like functionality to Python.

Here are a few examples of how to use NumPy.

First, we have to tell Python that it has to load the package using an `import` statement.
We also use a shorthand to refer to NumPy functions in upcoming calls.

In [1]:
import numpy as np

Next, we create some arrays from scratch, using the `list` datatype as closest representation to what we want.

In [3]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

This is a one-dimensional vector in NumPy.
It has no concept of row or column.

In [4]:
a.shape

(3,)

We can create two-dimensional arrays where one of the dimensions has size one in order to create row- or column-oriented vectors.

In [7]:
a.reshape([3, 1])

array([[1],
       [2],
       [3]])

In [9]:
a.reshape([1, 3])

array([[1, 2, 3]])

Here we also see how a matrix can be constructed starting from lists.
We do this by nesting lists: the "outermost" list groups rows in the matrix, while the "innermost" list groups elements in each row (effectively characterizing columns).

In [15]:
A = np.array([[100, 200, 300, 400],
              [ 50,  75,- 10,- 15],
              [  9,   8,   7,   6]], dtype=float)
A

array([[100., 200., 300., 400.],
       [ 50.,  75., -10., -15.],
       [  9.,   8.,   7.,   6.]])

Note that I specified the datatype (`dtype`) of all entries of the matrix `A` to be floating point numbers (as opposed to integers).
We can add static typing to our variables to improve performance of our algorithms, so that Python will not have to spend CPU cycles trying to infer the type of objects it is working with.

In [16]:
A.shape

(3, 4)

To access elements within a matrix we use the square brackets.

In [17]:
A[0, 3] = np.nan
A

array([[100., 200., 300.,  nan],
       [ 50.,  75., -10., -15.],
       [  9.,   8.,   7.,   6.]])

Note that indexing in Python is `0`-based: the number `0` represents the first element in an iterable object (e.g., a list, a matrix, etc.).
This means that for a matrix with dimensions `N`-by-`M`, we can refer to specific items using integers ranging from `0` to `N-1` for the rows, from `0` to `M-1` for the columns.

Note that Python supports "backward" indexing:

In [30]:
A[-1, -2]

7.0

The previous command looks for the element in the _last_ row, _second-to-last_ column of `A`.

NumPy supports a number of standard functions to create arrays that are somewhat regular.
Notable examples are empty matrices (`np.empty`), arrays full of zeros (`np.zeros`), arrays full of ones (`np.ones`), linearly, of logarithmically-spaced vectors (`np.linspace` and `np.logspace`), mesh grids (`np.mesh`) and so on.

In [27]:
n = 10+1
xLo = 0
xHi = 2
X = np.linspace(xLo, xHi, n)
X

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

It also provides mathematical functions that Python does not know, such as `np.sqrt`, `np.sin`, `np.log`, etc.

In [28]:
Y = np.sqrt(X)
np.hstack( [ X.reshape([-1, 1]), Y.reshape([-1, 1]) ] )

array([[0.        , 0.        ],
       [0.2       , 0.4472136 ],
       [0.4       , 0.63245553],
       [0.6       , 0.77459667],
       [0.8       , 0.89442719],
       [1.        , 1.        ],
       [1.2       , 1.09544512],
       [1.4       , 1.18321596],
       [1.6       , 1.26491106],
       [1.8       , 1.34164079],
       [2.        , 1.41421356]])

For now, this is all we need to know: NumPy brings multidimensional arrays and basic mathematical functions to Python, essentially approximating what Matlab can do (without its toolboxes).

However, we're missing mathematical and statistical routines (e.g., root-finding solver, sampler for known random variables).
This is where SciPy comes in.

### SciPy

    incomplete

### Matplotlib

    incomplete